name: On push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - name: 'install'
        run: npm ci
      - name: 'test'
        run: npm run test
      - name: 'types test'
        run: npm run ts
      - name: 'lint'
        run: npm run lint