name: simple push tag action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    tags:
      - 'rc-*.*.*'
jobs:
  new-tag-job:
    runs-on: ubuntu-latest
    steps:
       - run: echo "Now im generating release message"
       - run: echo "i think its a version tag:"
       - run: echo ${{ steps.vars.outputs.tag }}
       - run: echo "ответственный за релиз <имя того, кто запушил тег>"
       - run: echo "коммиты, попавшие в релиз:"
       - run: echo "<хеш коммита> <автор коммита> <описание коммита>"
       - run: echo "<хеш коммита> <автор коммита> <описание коммита>"
       - run: echo "<хеш коммита> <автор коммита> <описание коммита>"
       - run: echo "\n"
       - run: ls -la
       - run: pwd
      # - run: git log --pretty=format:'%h %an %s'   
