name: On push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  push-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Now im testing your commits"
      - run: echo "test 1"
      - run: echo "test 2"
      - run: echo "test 3"