name: simple push tag action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    tags:
      - 'rc-*.*.*'
jobs:
  new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - name: 'install'
        run: npm ci
      - name: 'test'
        run: npm run test
      - name: 'lint'
        run: npm run lint
      - name: Generate release message
        run: message=$(./.github/scripts/log-commits.sh)
      - name: Send tracker message
        run: ./.github/scripts/send-message.sh $message
        env:
          OAuth: ${{ secrets.OAUTH_TOKEN }}
          orgId: ${{ secrets.ORGANIZATION_ID }}
                
