name: simple push tag action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    tags:
      - 'rc-*.*.*'
jobs:
  new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - run: echo "Now im generating release message"
      - run: echo "i think its a version tag:"
      - run: echo ${{ steps.vars.outputs.tag }}
      - run: echo "\n"
      - run: pwd
      - run: ls -la
      - run: echo "Ответственный за релиз $(git log --pretty=format:'%an'  @^..@)"
      - run: echo "коммиты, попавшие в релиз:"
      - run: git log --pretty=format:'<%h> <%an> <%s>' $(git describe --tags @^ --abbrev=0)..
      - run: echo "Ответственный за релиз $(git log --pretty=format:'%an'  @^..@)\nкоммиты, попавшие в релиз:\n$(git log --pretty=format:'<%h> <%an> <%s>' $(git describe --tags @^ --abbrev=0)..)"
