name: simple push tag action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    tags:
      - 'rc-1.0.*'
jobs:
  new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - name: 'install'
        run: npm ci
      - name: 'test'
        run: npm run test
      - name: 'lint'
        run: npm run lint
      - name: Send release message to tracker
        run: |
              message=$(./.github/scripts/log-commits.sh)
              echo "release message successfully genereted ($message)"
              body=$(./.github/scripts/generate-body.sh description "$message")
              echo "body successfully genereted ($body)"
              ./.github/scripts/send-message.sh PATCH "$body"
              echo "release message loaded to tracker"
        env:
          OAuth: ${{ secrets.OAUTH_TOKEN }}
          orgId: ${{ secrets.ORGANIZATION_ID }}
      - name: Create docker image
        run: | 
              docker build . -f Dockerfile -t ${{ github.ref_name }}
              echo "bulded docker image"
      - name: Send notification about docker image to tracker comments
        run: |
              message="Собрал образ с тэгом ${{ github.ref_name }}"
              echo "comment message successfully genereted ($message)"
              body=$(./.github/scripts/generate-body.sh text "$message")
              echo "body successfully genereted ($body)"
              ./.github/scripts/send-message.sh POST "$body" comments
              echo "comment loaded to tracker"
        env:
          OAuth: ${{ secrets.OAUTH_TOKEN }}
          orgId: ${{ secrets.ORGANIZATION_ID }}

                
