name: simple push tag action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    tags:
      - 'rc-1.0.*'
jobs:
  new-tag-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16.16.0"
      - name: 'install'
        run: npm ci
      - name: 'test'
        run: npm run test
      - name: 'lint'
        run: npm run lint
      - name: Send release message to tracker
        run: |
              message=$(./.github/scripts/log-commits.sh)
              echo "release message successfully genereted"
              body=$(./.github/scripts/generate-body.sh description $message)
              echo "body successfully genereted"
              ./.github/scripts/send-message.sh "$body"
              echo "release message loaded to tracker"
        env:
          OAuth: ${{ secrets.OAUTH_TOKEN }}
          orgId: ${{ secrets.ORGANIZATION_ID }}
      # - name: Generating docker image
      #   run:
      #   env:
      #     OAuth: ${{ secrets.OAUTH_TOKEN }}
      #     orgId: ${{ secrets.ORGANIZATION_ID }}

                
